import { defineProperties, createSprinkles } from "@vanilla-extract/sprinkles";
import { style } from "@vanilla-extract/css";

import { fontSize, fontWeight } from "./typography.css";
import { borderRadius, borderSize, shadows } from "./border.css";
import { mediaSize, position, size, space } from "./size.css";
import palette from "./colors.css";

const responsiveProperties = defineProperties({
  conditions: {
    mobile: {},
    tablet: { "@media": "screen and (min-width: 768px)" },
    desktop: { "@media": "screen and (min-width: 1024px)" },
  },
  defaultCondition: "tablet",
  responsiveArray: ["mobile", "tablet", "desktop"],
  properties: {
    display: ["flex", "block", "inline-block", "inline", "grid", "none"],
    flexDirection: ["row", "column", "row-reverse", "column-reverse"],
    justifyContent: [
      "flex-start",
      "flex-end",
      "center",
      "space-between",
      "space-around",
      "space-evenly",
    ],
    alignItems: ["flex-start", "flex-end", "center", "stretch", "baseline"],
    alignContent: [
      "flex-start",
      "flex-end",
      "center",
      "stretch",
      "space-between",
      "space-around",
    ],
    flexWrap: ["nowrap", "wrap", "wrap-reverse"],
    flex: ["none", "auto", "initial", "inherit"],
    flexGrow: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    flexShrink: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    flexBasis: ["auto", "initial", "inherit"],
    order: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    alignSelf: [
      "auto",
      "flex-start",
      "flex-end",
      "center",
      "baseline",
      "stretch",
    ],
    justifySelf: ["auto", "flex-start", "flex-end", "center", "stretch"],
    gridTemplateColumns: ["none", "auto", "initial", "inherit"],
    gridTemplateRows: ["none", "auto", "initial", "inherit"],
    gridTemplateAreas: ["none", "auto", "initial", "inherit"],
    gridAutoColumns: ["auto", "initial", "inherit"],
    gridAutoRows: ["auto", "initial", "inherit"],
    gridAutoFlow: ["row", "column", "row dense", "column dense"],
    grid: ["none", "auto", "initial", "inherit"],
    gridColumn: ["auto", "initial", "inherit"],
    gridColumnStart: ["auto", "initial", "inherit"],
    gridColumnEnd: ["auto", "initial", "inherit"],
    gridRow: ["auto", "initial", "inherit"],
    gridRowStart: ["auto", "initial", "inherit"],
    gridRowEnd: ["auto", "initial", "inherit"],
    gridArea: ["auto", "initial", "inherit"],
    gridGap: space,
    gap: space,
    gridColumnGap: space,
    gridRowGap: space,
    placeContent: [
      "center",
      "start",
      "end",
      "stretch",
      "space-between",
      "space-around",
      "space-evenly",
    ],
    placeItems: ["center", "start", "end", "stretch", "baseline"],
    placeSelf: ["auto", "center", "start", "end", "stretch", "baseline"],
    overflow: ["visible", "hidden", "scroll", "auto"],
    overflowX: ["visible", "hidden", "scroll", "auto"],
    overflowY: ["visible", "hidden", "scroll", "auto"],
    position: ["static", "relative", "absolute", "fixed", "sticky"],
    paddingTop: space,
    paddingRight: space,
    paddingBottom: space,
    paddingLeft: space,
    padding: space,
    marginTop: space,
    marginRight: space,
    marginBottom: space,
    marginLeft: space,
    margin: space,
    top: position,
    right: position,
    bottom: position,
    left: position,
    width: { ...size, screen: "100vw" },
    height: { ...size, screen: "100vh" },
    minWidth: size,
    maxWidth: size,
    minHeight: size,
    maxHeight: size,
    fontSize: fontSize,
    fontWeight: fontWeight,
    lineHeight: ["none", "tight", "snug", "normal", "relaxed", "loose"],
    letterSpacing: ["tighter", "tight", "normal", "wide", "wider", "widest"],
    textAlign: ["left", "center", "right", "justify"],
  },
  shorthands: {
    paddingX: ["paddingLeft", "paddingRight"],
    paddingY: ["paddingTop", "paddingBottom"],
    marginX: ["marginLeft", "marginRight"],
    marginY: ["marginTop", "marginBottom"],
    insetX: ["left", "right"],
    insetY: ["top", "bottom"],
  },
});

const systemProperties = defineProperties({
  properties: {
    color: palette,
    backgroundColor: palette,
    borderColor: palette,
    borderRadius: borderRadius,
    borderWidth: borderSize,
    boxShadow: shadows,
    opacity: ["0", "25", "50", "75", "100"],
    cursor: [
      "auto",
      "default",
      "pointer",
      "wait",
      "text",
      "move",
      "not-allowed",
    ],
    pointerEvents: ["auto", "none"],
    userSelect: ["auto", "none", "text", "all", "contain"],

    fill: palette,
    stroke: palette,
    strokeWidth: ["0", "1", "2"],
    transitionProperty: [
      "none",
      "all",
      "default",
      "colors",
      "opacity",
      "shadow",
      "transform",
    ],
    transitionTimingFunction: ["linear", "in", "out", "in-out"],
    transitionDuration: [
      "75",
      "100",
      "150",
      "200",
      "300",
      "500",
      "700",
      "1000",
    ],
    transitionDelay: ["75", "100", "150", "200", "300", "500", "700", "1000"],
    animation: ["spin", "ping", "pulse", "bounce"],
  },
});

export const spice = createSprinkles(responsiveProperties, systemProperties);

export type Sprinkles = Parameters<typeof spice>[0];
